version: '3.8'

services:
  reactjs:
    image: reactjs
    container_name: reactjs
    build:
      context: .
      dockerfile: Dockerfile.development
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    env_file:
      - .env.development
