# Use node alpine as it's a small node image
FROM node:lts-alpine as nextjs-fe

LABEL author="Nasr Aldin"

RUN npm i -g pnpm

WORKDIR /app

COPY package.json pnpm-lock.yaml ./
RUN pnpm install

COPY tsconfig.json ./

EXPOSE 3000
CMD ["pnpm", "dev"]
